### PR TITLE
moved attribution icon to top left

### LINKED ISSUE #2022: Move attribution icon to top left corner on the map (mobile view)
### Overview
Based on feedback from the design team, attribution needs to be moved to the top left corner on the map for mobile view.

foodoasis la_organizations

### Action Items
- [ ] Move the attribution icon to the top left corner on the map.
- [ ] Make sure the functionalities are still the same.

### Resources/Instructions
- [Mapbox attribution](https://docs.mapbox.com/help/glossary/attribution/#:~:text=Mapbox%20attribution%20is%20the%20combination,with%20Mapbox%20tools%20and%20data)

### PR DESCRIPTION
**Pull request by SAUMILDHANKAR**
- Closes #2022  
- New

https://github.com/hackforla/food-oasis/assets/843538/7adebc79-34e7-47d1-b633-43fc53ad6c89

- Old

https://github.com/hackforla/food-oasis/assets/843538/a3720b91-c73d-433d-b5ce-c47fe9aef42f

### CODE REVIEW

**Comment by hanapotski** [comment]
is this where we want it to be? 🤔 it looks like it's colliding with the advanced filters 
Screen Shot 2024-03-04 at 6 30 34 PM

**Comment by SAUMILDHANKAR** [comment]
> is this where we want it to be? 🤔 it looks like it's colliding with the advanced filters Screen Shot 2024-03-04 at 6 30 34 PM

@hanapotski Thank you for catching that. 
@JohnHaoHuang Hi John, please guide us on the design/layout for the icons as seen in the image. Thank you.

**Comment by JohnHaoHuang** [comment]
If we do not show the map in full list view, can we omit the the info and mapbox icon? @SAUMILDHANKAR

**Comment by JohnHaoHuang** [comment]
@SAUMILDHANKAR Sorry for the delay. Please view the solution in Figma under March 16, 2024 update. Let me know if you have any other questions. Thanks.

https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640%3A125&mode=design&t=Jw7eBJxEJqr9e5x6-1

**Comment by SAUMILDHANKAR** [comment]
> @SAUMILDHANKAR Sorry for the delay. Please view the solution in Figma under March 16, 2024 update. Let me know if you have any other questions. Thanks.
> 
> https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640%3A125&mode=design&t=Jw7eBJxEJqr9e5x6-1

@JohnHaoHuang Thank you so much for sharing the design on Figma. Also need your help on the design for when the info icon is pressed. Please notice that on pressing the info icon some additional text appears as shown in the following clip:

https://github.com/hackforla/food-oasis/assets/843538/7adebc79-34e7-47d1-b633-43fc53ad6c89

My question is (as per your design) do we push the mapbox logo to the right when info icon is pressed? Another approach could be to have the info icon to the right of mapbox logo.

**Comment by JohnHaoHuang** [comment]
@SAUMILDHANKAR, Please review the new design in figma. Let me know if you have any questions. Thank you. 

https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640%3A125&mode=design&t=CHUVPwP7awyJemzQ-1

**Comment by SAUMILDHANKAR** [comment]
As per the design recommendation in Figma,
- Added 2.23px padding on top of info icon to make the gap between logo svg and icon 8 px.
- Fixed the y position of draggable component at 60px so that the gap between the button in advanced filter and the logo svg is 16px (since window.innerheight changes with device type). Adjusted the y position within handlestop as well.

https://github.com/hackforla/food-oasis/assets/843538/f8fb0337-dd96-4a65-b1de-b5c72843fb68

**Comment by SAUMILDHANKAR** [comment]
@hanapotski @qiqicodes Thank you for helping me on adding the padding, using ternary operator and using stack in place of grid. Requesting your review. Please see the following clip for the latest changes. Thank you.

https://github.com/hackforla/food-oasis/assets/843538/62be50d1-efa3-4316-8ca3-e285b0cf1b87

**Review by andyarensman — APPROVED** [review]
LGTM

**Comment by SAUMILDHANKAR** [comment]
@andyarensman Thank you so much for your review and approval.

@JohnHaoHuang Hi John, just wanted to share with you that the design request for mapbox logo and icon has now been merged to dev branch. Feel free to take a look at the mobile view on https://devla.foodoasis.net/organizations. Following clip shows the same as well. Hope it is fine. Thank you.

https://github.com/hackforla/food-oasis/assets/843538/62be50d1-efa3-4316-8ca3-e285b0cf1b87

**Pull request merged**
