### PR TITLE
proposes two options for `SwitchViewsButton` component

### PR DESCRIPTION
**Pull request by qiqicodes**
Style `SwitchViewsButton` component

**Current Styling:**

https://github.com/hackforla/food-oasis/assets/68657634/00ddd08d-2ea9-49e6-a42c-6f0f86f692c8

**proposed option 1 styling:**
- uses the existing button palette, and removes styled dependency to simplify the component

https://github.com/hackforla/food-oasis/assets/68657634/8cf403c8-66f9-4df2-965f-ae156be946f8

**proposed option 2 styling:**
- modifies the hover, active, focus state to keep the background color as white

https://github.com/hackforla/food-oasis/assets/68657634/c2ce2d42-5ae4-40b6-b9ac-14f509c66ce5

### CODE REVIEW

**Comment by JohnHaoHuang** [comment]
Nice work!. It would be nice to have the list slide up when the list icon is clicked.

**Comment by qiqicodes** [comment]
Implementes the proposed option 2 styling: where the `SwitchViewsButton` background color remains white for all state.

https://github.com/hackforla/food-oasis/assets/68657634/c2ce2d42-5ae4-40b6-b9ac-14f509c66ce5

**Comment by 93Belen** [comment]
The weird thing is that's not what the current styling looks like in mine. I did it the same as theis Figma file shows: https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-126&mode=design&t=tCDG1yy6W7AILBSR-0
Although there is this other design as well: https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-124&mode=design&t=tCDG1yy6W7AILBSR-0

**Comment by JohnHaoHuang** [comment]
> In Safari the styling is right, the blue background appears in Chrome, didn't realize that before. I did it the same as the Figma file shows: https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-126&mode=design&t=tCDG1yy6W7AILBSR-0 Although there is this other design as well: https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-124&mode=design&t=tCDG1yy6W7AILBSR-0

**Comment by JohnHaoHuang** [comment]
@93Belen Please follow the first Figma link that you've posted. The second Figma link is outdated. Sorry for the confusion. I've already made a note in the second Figma link stated that page is outdated.

**Comment by qiqicodes** [comment]
@JohnHaoHuang thanks for the clarification regarding the figma link. This PR matches the latest design and ready for merging once approved.

**Review by hanapotski — APPROVED** [review]

**Pull request merged**
