### PR TITLE
changed design back to search button

### LINKED ISSUE #2096: Update the Mobile "Back to Location" design for the Stakeholder Details
### Overview
The current design for the mobile "Back to Location" button is temporary. Update it to the new design when John completes it.

### Action Items
 - [x] wait for John's new design
 - [x] implement design for mobile view
 - [x] make sure desktop view isn't changed

### Resources/Instructions
The new design is on the bottom right of this Figma file under "When user clicks on the one of the location item, content details will display in full view. Back button is also added:"
https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/FOLA-Design-%232?type=design&node-id=640-125&mode=design&t=RBGUvkkY0MzvtejZ-0

current design:
chrome_eAKNBETsUN

new design:
chrome_ixqKR2e53z

### PR DESCRIPTION
**Pull request by 93Belen**
Closes #2096 

New design:
IMG_1474B5AD8D00-1

Desktop stays the same:
Screenshot 2024-05-15 at 8 13 45 AM

### CODE REVIEW

**Review by andyarensman — CHANGES_REQUESTED** [review]
Mobile version looks great, but I think designer John wants it to still say "Back to Location" for desktop. "Search" for mobile and "Location" for desktop

**Comment by 93Belen** [comment]
@andyarensman It should be ok now. I added one text for mobile and another for desktop :)

**Review by andyarensman — CHANGES_REQUESTED** [review]
For some reason it's not recognizing your font size on "back to location" for desktop view:

chrome_KBjPcbtoqd


Changing line 292 to ```fontSize: { md: "18px" },``` fixed it for me.

**Comment by 93Belen** [comment]
@andyarensman fixed! sorry I didn't check it properly 😅

**Review by andyarensman — APPROVED** [review]
LGTM

**Pull request merged**
