### PR TITLE
2108 stakeholder detail conditional back text

### LINKED ISSUE #2108: Stakeholder Details "Back to Location" text update
### Overview
In the Stakeholder Details side panel, the text to the right of "Back to Location" needs to be updated to match the categories of the location.

chrome_UNyKitPseN

### Action Items
- [ ] The text should read "Meal and Pantry", "Meal", or "Pantry" based on the category or categories of the location.

### PR DESCRIPTION
**Pull request by andyarensman**
Closes #2108 

The text next to "back to location" is now based on the categories of the location:
Screen Shot 2024-04-16 at 7 27 50 PM
Screen Shot 2024-04-16 at 7 26 32 PM
Screen Shot 2024-04-16 at 7 26 20 PM

### CODE REVIEW

**Comment by andyarensman** [comment]
Fixing based on Hannah's comments

**Comment by andyarensman** [comment]
@hanapotski I think this is more readable now

**Review by qiqicodes — COMMENTED** [review]
Food for thought: The current text display is based on the category details of the selected organization. Should we consider displaying the type of category selected by the user?

**Comment by andyarensman** [comment]
> Food for thought: The current text display is based on the category details of the selected organization. Should we consider displaying the type of category selected by the user?

@qiqicodes You're welcome to bring that up with the design team, but I don't think it's necessary at this point.

**Pull request merged**
