### PR TITLE
first pass on preview card changes

### PR DESCRIPTION
**Pull request by bbovenzi**
- icons are now jsx functions
- remove address from preview
- add buttons to previews
- reformat preview tags
- parse phone numbers to catch multiple

Screen Shot 2020-09-29 at 2 46 38 PM
Screen Shot 2020-09-29 at 2 46 45 PM

### CODE REVIEW

**Comment by bbovenzi** [comment]
@pageignited Still WIP but I wanted to get your initial feedback on this wrt to #695

**Comment by pageignited** [comment]
@bbovenzi This is looking great.

**Comment by pageignited** [comment]
No, I will put it out the team now

**Comment by bbovenzi** [comment]
fixes #695

**Comment by pageignited** [comment]
@bbovenzi @entrotech So the team gave their feedback on the button, and I did get sign off on them. There is a style guide we need to  follow here https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=0%3A1 

Brent, I add you to the Slack tread on what the design team wanted the look for the button.  They would like to go with  "dark grey with white background with dark grey border,"  so this will keep the user focused on the title of the org and the icons.

**Comment by pageignited** [comment]
Screen Shot 2020-10-01 at 12 52 13 PM

**Review by entrotech — APPROVED** [review]

**Pull request merged**
