### PR TITLE
1819 add drawer button to panel

### PR DESCRIPTION
**Pull request by junjun107**
close https://github.com/hackforla/food-oasis/issues/1819
closed
open

### CODE REVIEW

**Comment by andyarensman** [comment]
Should the panel be that wide?

**Comment by junjun107** [comment]
> Should the panel be that wide?



> Should the panel be that wide?

Thanks! I updated the width.

**Comment by andyarensman** [comment]
I'm seeing a flash of white on the right side of the screen when I close the drawer - anyone else seeing that?

**Comment by SAUMILDHANKAR** [comment]
> I'm seeing a flash of white on the right side of the screen when I close the drawer - anyone else seeing that?

I see that too.

**Review by qiqicodes — APPROVED** [review]
lgtm

**Pull request merged**
