### PR TITLE
ui cleanup on search card

### PR DESCRIPTION
**Pull request by lucas-homer**
- Some general ui cleanup to make it a little more responsive across mobile and desktop sizes. 

- Tweaked the button to switch between list and map views to hopefully make it more obviously a button to switch views. 

https://www.loom.com/share/e3b2a94879604c2cbf46933be6275f4e

### CODE REVIEW

**Comment by chombus** [comment]
@lucas-homer This control seems important while a user views results so maybe move the button closer to that content.
image 


Also the addition of a label definitely helps, but I would go one step further and add an outline to the button. See the outlined button in material design specs: https://material.io/components/buttons/# What do you think?

**Comment by lucas-homer** [comment]
1) I like that idea to move the view toggle button down closer to the map. 2) That reinforces the idea I also had to turn this entire search card into an [Expansion Panel](https://material-ui.com/components/expansion-panels/), and then you can collapse the card and have more room for the map/list.

**Comment by tina-moh** [comment]
Hi everyone, 
Since the website is map based search, I suggest :
- Toggle full screen view ( which increase usability and visibility especially on mobile screen due 
   to small dimensions) 
- Expansion Panel by click on each location on map that describes the place :
   .  Address
   .  Phone icon / number visible on click /Can dial by clicking on number
   .  Clock Icon (visible hours for just the day user is searching (possible ???)  - weekly 
      hours visible by a little chevron)
   .  Website ( linked to place website on click)
   .  Direction ( linked to google maps )

**Comment by lucas-homer** [comment]
Thanks for responding, @tina-moh ! I'd like to chat some more on Tuesday night about this topic.

**Pull request merged**
