### PR TITLE
Usability: No ‘enter’ button on location search field #1668

### LINKED ISSUE #1668: Usability: No ‘enter’ button on location search field
### Overview
On search fields, there is usually an on-screen ‘search’ button that submits the text entry to the search engine.  However, our landing page does not have this, so we are breaking with a popular UI pattern.

We basically require a user to press the ‘enter’ button on their on-screen keyboard to submit a text field — but this isn’t obvious, especially if the user selects an auto-complete item.

IMG_2804

This happens on both desktop and mobile landing pages, but it’s worse on mobile since users may not know they have to hit the ‘enter’ key on their on-screen keyboard.

### Discussion and possible Solution(s)
Suggest: 
- [x] Make the magnifying glass into a more obvious button by changing its color (it’s actually a button — try it — it goes to Los Angeles)  
- [x] Keep the magnifying glass button in the text field visible while the user enters text. 

#### Quick mockup of current the suggested solution
image

### Action Items

- [x] Confirm that this is a problem worth fixing (research, design teams)
- [x] Investigate problem
- [ ] Problems seem to be:
  - [ ] No ‘submit’ button, which we can fix by adding one (easy to fix - see above sketch)
  - [x] #1691
  - [ ] #1692
- [ ] Design and specify changes (design)
- [ ] Implement changes (devs)
- [ ] Beta test / QA (design, research)

### PR DESCRIPTION
**Pull request by Sage-2001**
Added a Search button on the website. Need some more bug fixes #1668

### CODE REVIEW

**Comment by fancyham** [comment]
Hi — is there a working dev version I can check out? :)

**Comment by fancyham** [comment]
Screenshots would be fine

**Comment by Sage-2001** [comment]
> Screenshots would be fine

Here are some screenshots on cursor hover the search button turns purple 
Capture

**Comment by fancyham** [comment]
Hi there — Please check out this issue for the site-wide button styles — I think our standard is rectangular site-wide (oval buttons may be used later)

https://github.com/hackforla/food-oasis/issues/1518 

I’m also going to forward these screen shots to the design team since these are kind of unusual… just curious as a possible option: is it also easily possible to put the button inside the form field?

**Comment by Sage-2001** [comment]
> Hi there, thanks for the screenshots. Please check out this issue for the [site-wide button styles ](https://github.com/hackforla/food-oasis/issues/1518) — I think our standard is rectangular site-wide. Could you revise and add the new screenshots?
> 
> I’m also going to forward these screenshots to the design team since these are kind of unusual… just curious as to a possible option: is it also easily possible to put the button inside the form field?
Uploading Desktop Screenshot 2023.06.04 - 16.38.46.
![Desktop Screenshot 2023 06 04 - 16 38 38 19
63.png…]()

Yeah sure i can put the button inside the form field these are sample screenshots if any changes needed let me know

**Comment by Sage-2001** [comment]
> Hi there, thanks for the screenshots. Please check out this issue for the [site-wide button styles ](https://github.com/hackforla/food-oasis/issues/1518) — I think our standard is rectangular site-wide. Could you revise and add the new screenshots?
> 
> I’m also going to forward these screen shots to the design team since these are kind of unusual… just curious as a possible option: is it also easily possible to put the button inside the form field?
Desktop Screenshot 2023 06 04 - 16 40 41 28
Desktop Screenshot 2023 06 04 - 16 38 46 63


Here are some sample screenshots, please let me know if they are up to the mark or if some changes are needed to be made. I have moved the button inside the form field. I will make the PR accordingly.

**Comment by entrotech** [comment]
In order to contribute to Hack for LA projects, you must first go through the onboarding process and join Hack for LA as described on the [contributing page of the repo](https://github.com/hackforla/food-oasis). The instructions for joining can be found [here](https://www.hackforla.org/join).

**Pull request closed without merging**
