### PR TITLE
Update Styling System to Use xs Prop in Material-UI Components (FAQ)

### LINKED ISSUE #1705: Update Styling System to Use xs Prop in Material-UI Components
### Overview
Our project currently utilizes the makeStyles function for styling Material-UI components. However, with the updates in Material-UI version 5, it is recommended to transition to using the sx prop for styling. 
Additionally, once we don't use the makeStyles function, we will be able to remove the `mui/styles` dependency, which has conflicts with React v.18 recently added to our project. 
This GitHub issue aims to update the styling system in our project. For now, we are going to start the change in the FAQ page in `components/StaticPages/Faq.js`

### Action Items
- [x] Replace HTML elements with Material Ui components
- [x] Replace the existing makeStyles implementation with the xs prop for styling in the FAQ page.
- [x] Ensure that the changes do not impact the styling overrides in the theme folder.
- [x] Make sure you don't lose accessibility when replacing semantic HTML for Material UI Components
- [ ] Resolve dependency conflicts

### Resources/Instructions
https://mui.com/material-ui/getting-started/overview/
https://mui.com/material-ui/migration/migration-v4/

### PR DESCRIPTION
**Pull request by 93Belen**
Fixes #1705

- Replaced HTML with Material-UI Components
- Added styles in `sx` prop
- Added `variants` to Typography components to follow override themes and have a consistent styling
- Used breakpoints instead of `@meadia query px` to follow project themes and have a consistent styling
- Removed `<figure>` element and added `component="img"` to CardMedia to ensure accessibility
- Changed `<dt> <dl> and <dd>` elements for `<Box>` with component prop
- Removed `makeStyles` function and unused elements and imports
- Added React Component that returns SVG icon in `assests/IconSpacerSVG.js` so I can use Material-UI's SVGIcon correctly
- I used a screen reader to make sure it works as before despite the changes in the HTML
_Some breakpoints, measures and font-sizes changed slightly by using variants and provided breakpoints, but these will end up matching in the whole project once all the styles are updated. Using theses provided styles will facilitate future maintenance and styling of the website._

<details><summary>Video of current Web Page</summary>

> https://github.com/hackforla/food-oasis/assets/98275292/c43410df-7aad-4c70-aef7-2e544f3d45f7

</details>

<details><summary>Video after changes</summary>

> https://github.com/hackforla/food-oasis/assets/98275292/f51dacec-a64f-40a0-905e-e9a30a845e7a

</details>

### CODE REVIEW

**Comment by hanapotski** [comment]
I think we lost some top padding and the texts looks a little bit smaller? is it smaller on the mockup? 🤔 
Screen Shot 2023-07-08 at 4 28 17 PM

**Comment by 93Belen** [comment]
@hanapotski Yes sorry! I just fixed it. I did "padding: 0 2rem" for bigger screen sizes and it's "padding 1.5rem 2rem". It should be good now :)

**Comment by kurikurichan** [comment]
Hellooo, I've been referring to your code for updating the MUI styling on the contact form :) Perhaps for the SVG component, we can add a "color" parameter and then that way we can use that 1 component instead of making 3 different components all with different colors? I am using the same one but in grey instead of that particular color.

**Comment by 93Belen** [comment]
> Hellooo, I've been referring to your code for updating the MUI styling on the contact form :) Perhaps for the SVG component, we can add a "color" parameter and then that way we can use that 1 component instead of making 3 different components all with different colors? I am using the same one but in grey instead of that particular color.

Hey @kurikurichan that sounds good! but I need this pull request to get reviewed and merged. It's been waiting for a long time and the longer that is open the more chances there is gonna be a Merging conflict, so once that is done I will update the element you are referring too, ok?

**Pull request merged**
