### PR TITLE
Show list when clicking map

### PR DESCRIPTION
**Pull request by 93Belen**
Fixes: #2090 
I added some things to the App State so the Draggable Element with the List Result goes up when clicking the map

https://github.com/hackforla/food-oasis/assets/98275292/6399c07c-9175-41f1-bb44-49f8fff8e7c9

### CODE REVIEW

**Review by andyarensman — COMMENTED** [review]
When the Map/List button is on List, the panel doesn't snap up. Is that the intended behavior?

https://github.com/hackforla/food-oasis/assets/86622025/0ab5d26d-6cf3-40c4-ad58-e403e879a3d5

**Comment by 93Belen** [comment]
Sorry I didnt test that, I'll fix it, thanks!

**Comment by 93Belen** [comment]
@andyarensman I think is working now. I've been wrestling with Git but It looks like I haven't broken anything haha. Now the List goes up when clicking the map regardless of what the Map/List button is set to.

**Review by andyarensman — APPROVED** [review]
LGTM

**Pull request merged**
