### PR TITLE
removed unused components and variables

### LINKED ISSUE #1869: Fix warnings
### Overview
Client compiled with warnings:
Screen Shot 2023-10-10 at 11 03 21 AM

### PR DESCRIPTION
**Pull request by qiqicodes**
- closes #1869 
Screen Shot 2023-10-10 at 11 11 54 AM

### CODE REVIEW

**Review by junjun107 — COMMENTED** [review]
TagAdmin and VerificationAdmin are also being removed in [ PR #1872](https://github.com/hackforla/food-oasis/pull/1872/files#diff-03329df3ccdc3cc4d97e8194e45ac07a9545dfaeb52a100b668ac9881efa15c9)

**Comment by qiqicodes** [comment]
> TagAdmin and VerificationAdmin are also being removed in [ PR #1872](https://github.com/hackforla/food-oasis/pull/1872/files#diff-03329df3ccdc3cc4d97e8194e45ac07a9545dfaeb52a100b668ac9881efa15c9)

the working branch for PR #1872 is rebased on this branch and dependent on merging this pull request

**Comment by junjun107** [comment]
closes https://github.com/hackforla/food-oasis/issues/1865

**Review by junjun107 — APPROVED** [review]
LGTM

**Pull request merged**
